languange: node_js
node_js:
  - stable
script:
  - npm install -g vuepress@>=0.14.11
  - npm install
  - npm run docs:build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local_dir: docs/.vuepress/dist
  on:
    branch: master
